services:
  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - SPARK_MASTER_PORT=7077
      - SPARK_MODE=master
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 256M
    volumes:
      - ./:/opt/bitnami/spark/MultiExecutorPySparkSim
    networks:
      - spark-net

  spark-worker:
    image: bitnami/spark:latest
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_MODE=worker
    ports:
      - "8081-8084:8081"
    deploy:
      replicas: 4
      resources:
        limits:
          cpus: '2.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 256M
    volumes:
      - ./:/opt/bitnami/spark/MultiExecutorPySparkSim
    networks:
      - spark-net

networks:
  spark-net:
    driver: bridge